# Generated by Django 5.2.8 on 2025-11-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('unpublished', 'unpublished')], default='pending', max_length=20),
        ),
    ]
