# Generated by Django 5.2.8 on 2025-11-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('published', 'published')], default='pending', max_length=20),
        ),
    ]
