# Generated by Django 5.2.8 on 2025-11-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
