# Generated by Django 5.2.8 on 2025-11-21 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0010_remove_comment_reply_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='PostApp.comment'),
        ),
    ]
