# Generated by Django 5.2.8 on 2025-11-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0011_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
