# Generated by Django 5.2.8 on 2025-11-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0012_rename_content_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
