# Generated by Django 5.2.8 on 2025-11-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0014_comment_is_reply_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
    ]
