# Generated by Django 5.2.8 on 2025-11-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0016_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
