# Generated by Django 5.2.8 on 2025-11-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0017_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('published', 'published')], default='published', max_length=20),
        ),
    ]
