# Generated by Django 5.2.8 on 2025-12-05 20:19

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0019_remove_post_like_count_likedpost_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content'),
        ),
    ]
