# Generated by Django 5.2.8 on 2025-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0021_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
