# Generated by Django 5.2.8 on 2025-12-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0022_post_post_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
    ]
