# Generated by Django 5.2.8 on 2025-12-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_alter_loginattempts_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempts',
            name='is_locked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
