# Generated by Django 5.2.8 on 2025-12-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0003_alter_loginattempts_is_locked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginAttempts',
        ),
    ]
