name: CI/CD

on:
  push:
    branch: [ 'main' ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # -------- CI (Build + Validate) --------
    - name: Build Images
      run: docker-compose build

    - name: Start container with validation
      run: docker-compose up -d

    - name: Check if containers are running
      run: docker-compose ps

    - name: Stop container
      run: docker-compose down

    # -------- PUSH --------
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Images
      run: docker-compose push

    # -------- CD --------
    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/BlogApp
          docker compose pull
          docker compose down
          docker compose up -d

    # -------- MONITOR --------
    - name: Health check
      run: |
        sleep 15
        curl -f http://${{ secrets.SERVER_IP }}:8000 || exit 1