# Generated by Django 5.2.8 on 2025-12-16 13:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('book_file', models.FileField(upload_to='')),
                ('is_bought', models.BooleanField(default=False)),
            ],
        ),
    ]
